// POST /auto-release-cron
// Not called by users — scheduled via pg_cron, every 6 hours.
//
// ── THIS FUNCTION NO LONGER MOVES MONEY ─────────────────────────────────────
// Until 2026-08-06 this job transferred the seller's proceeds whenever
// auto_release_at passed with no buyer confirmation. That meant buyer silence
// was treated as consent: a buyer who never received the car, or who simply
// stopped reading email, paid the seller in full on a timer. Nothing in the
// system knew whether the car had changed hands, and nothing asked.
//
// Funds now leave escrow on exactly two signals, both requiring a live human:
//   • release-funds     — the buyer taps Confirm Receipt
//   • confirm-handover  — the seller enters the buyer's 6-digit handover code
//
// What this job does instead:
//   • warns BOTH parties 48h and 24h before the review deadline
//   • at the deadline, sets listings.review_flagged_at and alerts the admin
//   • never transfers, never marks sold, never touches funds_released
//
// The transfer block, the Stripe client, the source_transaction sourcing and
// settleReferral all moved to confirm-handover. They are gone from here on
// purpose — this function no longer has any reason to hold Stripe credentials,
// and an unattended job that cannot move money cannot move it wrongly.
//
// ── WHY NOT JUST REFUSE TO RELEASE FOREVER ──────────────────────────────────
// Because the mirror failure is just as bad: the seller hands over the car, the
// buyer never confirms, and the seller is out a vehicle and the money with no
// way to force resolution. Neither party's silence may be read as consent. So
// silence routes to a human — you — rather than defaulting to either side.
//
// ── auto_release_at KEPT, MEANING CHANGED ───────────────────────────────────
// The column, the guard_listings_handover trigger, the stripe-webhook write and
// the create-checkout-session cap all stay exactly as shipped on 2026-08-05. It
// now marks the ESCALATION deadline rather than the payment date. Where a
// handover_date was set, escalation correctly waits until a week after the car
// was due to change hands. Where none was set, the deadline is payment + 7d and
// the worst case is a review email about a sale that has not happened yet —
// a false positive, not a lost car.
//
// A flagged listing stays 'pending_confirmation'. It is NOT given a new status,
// so if the buyer surfaces late and confirms, or the seller finally enters the
// code, the sale completes on its own with no admin action.
//
// This function is unattended by definition — nobody is watching a response.
// Alerts are awaited rather than fire-and-forget.
//
// Deployed with --no-verify-jwt since the scheduler isn't a logged-in user.
// That is NOT the same as no authentication: the handler checks a bearer token
// itself (see below). Before 2026-08-07 it checked nothing, so anyone who knew
// the URL could drive it. It cannot move money, but it can email both parties
// that their sale has been paused and set review_flagged_at — enough to sow
// doubt in a live transaction on demand.
//
// The token is CRON_SHARED_SECRET, generated by us and held in two places: the
// Vault secret the pg_cron job reads, and the Edge Function secret this file
// reads. Deliberately NOT the service-role key — that was the first attempt
// and it failed. Supabase injects SUPABASE_SERVICE_ROLE_KEY into the function,
// and on a project migrated to JWT signing keys the injected value need not be
// byte-identical to the legacy service_role key on the API Keys page. Both
// sides held a valid key and the comparison still failed. One secret we own,
// one source of truth.
//
// Rotating it means updating BOTH the Vault secret and the function secret.
import {
  corsHeaders,
  jsonResponse,
  notifyAdminSync,
  alertHtml,
  money,
  supabaseAdmin,
} from "../_shared/helpers.ts";

// Authenticates the scheduler. See the note above on why this is not the
// service-role key. supabaseAdmin() in _shared still uses that key for the
// database client — this constant is only about who is allowed to call in.
const CRON_SECRET = Deno.env.get("CRON_SHARED_SECRET");

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY")!;
const FROM = "DriveLink <noreply@drivelink.deals>";
const SITE = "https://drivelink.deals";

// Local rather than shared: these are the only user-facing emails this job
// sends, and inlining them keeps the escrow-safety change to three files.
async function sendUserEmail(to: string, subject: string, html: string) {
  if (!to) return false;
  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ from: FROM, to, subject, html }),
    });
    if (!res.ok) {
      console.error(`Resend failed for ${to}:`, await res.text());
      return false;
    }
    return true;
  } catch (e) {
    console.error(`Resend threw for ${to}:`, e);
    return false;
  }
}

function shell(heading: string, body: string) {
  return `
  <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;color:#1a1a1a">
    <h2 style="font-size:18px;margin:0 0 16px">${heading}</h2>
    ${body}
    <p style="font-size:13px;color:#666;margin-top:28px;border-top:1px solid #eee;padding-top:16px">
      DriveLink · <a href="${SITE}" style="color:#B87300">drivelink.deals</a>
    </p>
  </div>`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  // Authorization. The `!expected` arm matters as much as the comparison: if
  // CRON_SHARED_SECRET were ever unset, a naive check would accept a bare
  // "Bearer " and hand an anonymous caller the whole job.
  const expected = CRON_SECRET ? `Bearer ${CRON_SECRET}` : null;
  if (!expected || req.headers.get("Authorization") !== expected) {
    console.warn("auto-release-cron: rejected unauthorized request");
    return jsonResponse({ error: "unauthorized" }, 401);
  }

  const supabase = supabaseAdmin();
  const results: Array<{ listing_id: string; action: string; detail?: string }> = [];

  try {
    const now = Date.now();

    // Every open escrow, not only the overdue ones — the 48h and 24h warnings
    // fire before auto_release_at, so filtering on lte() here would mean the
    // warnings never send.
    const { data: openSales, error } = await supabase
      .from("listings")
      .select(
        "id, seller_id, buyer_id, seller_net, sale_price, status, funds_released, auto_release_at, handover_date, review_flagged_at, handover_warned_48h_at, handover_warned_24h_at, make, model, year",
      )
      .eq("status", "pending_confirmation")
      .eq("funds_released", false);

    if (error) throw error;

    for (const listing of openSales ?? []) {
      const carLabel =
        [listing.year, listing.make, listing.model].filter(Boolean).join(" ") || listing.id;

      if (!listing.auto_release_at) {
        results.push({ listing_id: listing.id, action: "skipped_no_deadline" });
        continue;
      }

      const deadline = new Date(listing.auto_release_at).getTime();
      const hoursLeft = (deadline - now) / 3_600_000;

      // Fetch both parties once — needed by every branch below.
      const { data: parties } = await supabase
        .from("users")
        .select("id, name, email")
        .in("id", [listing.seller_id, listing.buyer_id].filter(Boolean));

      const buyer = parties?.find((u) => String(u.id) === String(listing.buyer_id));
      const seller = parties?.find((u) => String(u.id) === String(listing.seller_id));

      // ── Past the deadline: escalate once ────────────────────────────────
      if (hoursLeft <= 0) {
        if (listing.review_flagged_at) {
          results.push({ listing_id: listing.id, action: "already_flagged" });
          continue;
        }

        await supabase
          .from("listings")
          .update({ review_flagged_at: new Date().toISOString() })
          .eq("id", listing.id);

        // One question to each party, because the two answers mean opposite
        // things: "the car never arrived" is a refund, "I got it and forgot to
        // confirm" is a release. Nothing here should guess which.
        const askBody = `
          <p>The escrow on your <strong>${carLabel}</strong> sale has been open for a while
          with no confirmation, so we've paused it for review. <strong>The money is safe and
          has not moved.</strong></p>
          <p style="background:#FFF8E7;border-left:3px solid #FFB020;padding:12px 14px;margin:18px 0">
            <strong>Reply to this email with one line: has the car changed hands yet?</strong>
          </p>
          <p style="font-size:14px;color:#444">If it has, the buyer can confirm receipt in the app,
          or the seller can enter the buyer's 6-digit handover code — either releases the funds
          straight away. If it hasn't, tell us and we'll sort it out.</p>`;

        const sentBuyer = await sendUserEmail(
          buyer?.email ?? "",
          `Action needed — your ${carLabel} purchase is on hold`,
          shell("We've paused this transaction", askBody),
        );
        const sentSeller = await sendUserEmail(
          seller?.email ?? "",
          `Action needed — your ${carLabel} sale is on hold`,
          shell("We've paused this transaction", askBody),
        );

        await notifyAdminSync({
          subject: `🔍 Escrow escalated to review — ${carLabel} (${money(Number(listing.sale_price))})`,
          html: alertHtml("Sale passed its deadline with no confirmation", [
            ["Vehicle", carLabel],
            ["Sale price", money(Number(listing.sale_price))],
            ["Held from seller", money(Number(listing.seller_net))],
            ["Buyer", `${buyer?.name ?? "—"} (${buyer?.email ?? "—"})`],
            ["Seller", `${seller?.name ?? "—"} (${seller?.email ?? "—"})`],
            ["Handover date", listing.handover_date ?? "not set"],
            ["Deadline was", listing.auto_release_at],
            ["Buyer emailed", sentBuyer ? "yes" : "FAILED"],
            ["Seller emailed", sentSeller ? "yes" : "FAILED"],
            ["Listing ID", listing.id],
          ], "NO MONEY MOVED. Both parties were asked whether the car changed hands. Resolve manually: if received, have the buyer confirm or the seller enter the handover code. If not received, refund from the Stripe dashboard — check the refund window has not lapsed."),
        });

        results.push({ listing_id: listing.id, action: "flagged_for_review" });
        continue;
      }

      // ── 24h warning ─────────────────────────────────────────────────────
      if (hoursLeft <= 24 && !listing.handover_warned_24h_at) {
        const body = `
          <p>Your <strong>${carLabel}</strong> transaction is still awaiting confirmation.
          Tomorrow we'll pause it and check in with both of you.</p>
          <p style="font-size:14px;color:#444"><strong>Buyer:</strong> if you have the car and
          the signed title, confirm receipt in the app to release the funds — or give the seller
          your 6-digit handover code in person.<br>
          <strong>Seller:</strong> once the buyer has the car and title, ask them for their code
          and enter it to get paid.</p>
          <p><a href="${SITE}" style="display:inline-block;background:#FFB020;color:#111;padding:10px 18px;border-radius:6px;text-decoration:none;font-weight:600">Open DriveLink</a></p>`;

        await sendUserEmail(buyer?.email ?? "", `Tomorrow: your ${carLabel} escrow gets paused`, shell("One more day", body));
        await sendUserEmail(seller?.email ?? "", `Tomorrow: your ${carLabel} escrow gets paused`, shell("One more day", body));

        await supabase
          .from("listings")
          .update({ handover_warned_24h_at: new Date().toISOString() })
          .eq("id", listing.id);

        results.push({ listing_id: listing.id, action: "warned_24h" });
        continue;
      }

      // ── 48h warning ─────────────────────────────────────────────────────
      if (hoursLeft <= 48 && !listing.handover_warned_48h_at) {
        const body = `
          <p>Your <strong>${carLabel}</strong> transaction is still open. If nothing changes
          in the next two days we'll pause it and ask you both what happened. The money stays
          in escrow either way.</p>
          <p style="font-size:14px;color:#444"><strong>Buyer:</strong> confirm receipt once the
          car and signed title are in your hands.<br>
          <strong>Seller:</strong> enter the buyer's 6-digit handover code after they take the car.</p>
          <p><a href="${SITE}" style="display:inline-block;background:#FFB020;color:#111;padding:10px 18px;border-radius:6px;text-decoration:none;font-weight:600">Open DriveLink</a></p>`;

        await sendUserEmail(buyer?.email ?? "", `Your ${carLabel} escrow is still open`, shell("Two days left", body));
        await sendUserEmail(seller?.email ?? "", `Your ${carLabel} escrow is still open`, shell("Two days left", body));

        await supabase
          .from("listings")
          .update({ handover_warned_48h_at: new Date().toISOString() })
          .eq("id", listing.id);

        results.push({ listing_id: listing.id, action: "warned_48h" });
        continue;
      }

      results.push({ listing_id: listing.id, action: "no_action", detail: `${Math.round(hoursLeft)}h left` });
    }

    return jsonResponse({ processed: results.length, results });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown error";
    console.error("auto-release-cron error:", err);

    // pg_cron logs "succeeded" as long as the HTTP post was queued, so without
    // this alert the job can fail silently for weeks — which is what happened
    // between 2026-07-22 and 2026-07-27 with a stale column reference.
    await notifyAdminSync({
      subject: "⚠️ auto-release-cron failed",
      html: alertHtml("Escrow monitoring job errored", [
        ["Error", msg],
        ["Time", new Date().toISOString()],
      ], "No warnings sent and no sales escalated on this run. No money was at risk — this job no longer moves funds — but stalled sales are going unnoticed."),
    });

    return jsonResponse({ error: msg }, 500);
  }
});
