// expire-stale-wires
//
// Domestic wire rail abandonment handling. PHASE2_WIRE_RAIL_SPEC.md §6.
// stripe-webhook only fires when Stripe has something to report — a wire
// that never arrives produces no event at all, so nothing there ever
// notices a buyer who started a wire and then vanished. This cron is what
// notices instead.
//
// DORMANT UNTIL create-wire-session SHIPS: this build session is
// backend-only (PHASE2_WIRE_RAIL_SPEC.md §10 / the 2026-08-28 build
// decision) — create-wire-session, the function that actually sets
// funding_type = 'wire' and payment_started_at on a listing, was not built.
// Until it is, and until the customer_balance payment method is turned on
// at checkout, the query below matches zero rows and this function is a
// no-op every time it fires. Deploying it now is still worth doing: it
// means the abandonment safety net is already live the moment the
// full-stack wire session ships create-wire-session, instead of being a
// second thing that has to be remembered and deployed together with it.
//
// Query: listings where status = 'awaiting_payment' AND funding_type =
// 'wire' AND payment_started_at is old enough to need action.
//
//   - Day 2 (calendar days — deliberately NOT business days, unlike the
//     timeout below; the spec says "Day 2" plainly, and a short buyer nudge
//     shouldn't wait out a weekend the way the multi-day abandonment timeout
//     should): reminder email to the buyer. One-shot via
//     wire_reminder_sent_at, so a redelivered / re-run cron tick doesn't
//     resend it. trg_reset_listing_notice_flag-style un-stamping isn't
//     needed here the way nudge-stale-listings needs it for renewed
//     listings — a wire-parked listing's payment_started_at never resets in
//     place; a fresh attempt gets a fresh row via create-wire-session.
//   - At WIRE_ABANDONMENT_TIMEOUT_BUSINESS_DAYS (10 business days,
//     _shared/helpers.ts): BOTH auto-reopen the listing to 'active' (same
//     as checkout.session.async_payment_failed does for a bounced ACH
//     debit) AND notifyAdmin. Confirmed with Lampros 2026-08-28 — "alert
//     rather than fire silently" from the Aug 25 decision, "auto-reopen +
//     alert, both" from the Aug 28 confirmation. A car does not sit locked
//     forever, and a human still finds out to chase the wire.
//
// AUTH: CRON_SHARED_SECRET, generated by us and stored in both Vault (for
// the pg_cron job to read) and this function's Edge Function secrets. NOT
// the service-role key — see expire-stale-acceptances's header for why that
// failed on this project (JWT signing key migration, the injected
// SUPABASE_SERVICE_ROLE_KEY not matching the legacy key shown in the
// dashboard). Rotating it means updating BOTH the Vault secret and the
// function secret; they're compared byte-for-byte.
//
// Deploy:
//   supabase functions deploy expire-stale-wires --no-verify-jwt
//
// Dry run (changes nothing, reports what WOULD happen):
//   curl "https://<ref>.supabase.co/functions/v1/expire-stale-wires?dry=1" \
//     -H "Authorization: Bearer <CRON_SHARED_SECRET>"
//
// Every run logs a line whether or not it changed anything — auto-release-cron
// sat dead for weeks once because a broken run and an idle run looked
// identical from the outside (see its header for the 2026-07-22 to
// 2026-07-27 incident). notifyAdminSync in the outer catch is mandatory for
// the same reason: pg_cron logs success as soon as the HTTP POST is queued,
// not when the handler actually finishes.

import {
  supabaseAdmin,
  jsonResponse,
  notifyAdmin,
  notifyAdminSync,
  sendEmail,
  alertHtml,
  money,
  addBusinessDays,
  WIRE_ABANDONMENT_TIMEOUT_BUSINESS_DAYS,
} from "../_shared/helpers.ts";

const CRON_SECRET = Deno.env.get("CRON_SHARED_SECRET");
const REMINDER_AFTER_CALENDAR_DAYS = 2;

Deno.serve(async (req) => {
  // The `!expected` arm matters as much as the comparison: if
  // CRON_SHARED_SECRET were ever unset, a naive check would accept a bare
  // "Bearer " and hand this endpoint to anyone. Refuse instead.
  const expected = CRON_SECRET ? `Bearer ${CRON_SECRET}` : null;
  if (!expected || req.headers.get("Authorization") !== expected) {
    console.warn("expire-stale-wires: rejected unauthorized request");
    return jsonResponse({ error: "unauthorized" }, 401);
  }

  const startedAt = Date.now();
  const dryRun = new URL(req.url).searchParams.get("dry") === "1";
  const supabase = supabaseAdmin();

  const results = {
    considered: 0,
    reminded: 0,
    reminderSkipped: 0,
    reminderFailed: 0,
    expired: 0,
    expireFailed: 0,
    errors: [] as string[],
  };

  try {
    const now = new Date();

    const { data: candidates, error: readErr } = await supabase
      .from("listings")
      .select(
        "id, make, model, year, seller_id, buyer_id, payment_started_at, wire_reminder_sent_at, sale_price",
      )
      .eq("status", "awaiting_payment")
      .eq("funding_type", "wire")
      .not("payment_started_at", "is", null);

    if (readErr) {
      console.error("expire-stale-wires: read failed", readErr.message);
      return jsonResponse({ ok: false, stage: "read", error: readErr.message }, 500);
    }

    results.considered = candidates?.length ?? 0;

    for (const listing of candidates ?? []) {
      try {
        const startedAtDate = new Date(listing.payment_started_at as string);
        if (!Number.isFinite(startedAtDate.getTime())) {
          results.errors.push(`${listing.id}: unparseable payment_started_at`);
          continue;
        }

        const carLabel =
          [listing.year, listing.make, listing.model].filter(Boolean).join(" ") || listing.id;

        const timeoutAt = addBusinessDays(startedAtDate, WIRE_ABANDONMENT_TIMEOUT_BUSINESS_DAYS);
        const isTimedOut = now.getTime() >= timeoutAt.getTime();

        // ── Timeout: auto-reopen + alert, both ──────────────────────────
        if (isTimedOut) {
          if (dryRun) {
            results.expired++;
            continue;
          }

          // Guard on the same status this query selected for — a redelivered
          // / re-run cron tick must not reopen a listing that has since
          // settled via a late payment_intent.succeeded.
          const { data: reopened, error: reopenErr } = await supabase
            .from("listings")
            .update({ status: "active", buyer_id: null, stripe_payment_intent_id: null })
            .eq("id", listing.id)
            .eq("status", "awaiting_payment")
            .select("id")
            .maybeSingle();

          if (reopenErr) {
            results.expireFailed++;
            results.errors.push(`${listing.id}: reopen failed — ${reopenErr.message}`);
            continue;
          }

          if (!reopened) {
            // Status changed underneath us — the wire settled (or something
            // else moved the listing) between the read above and this write.
            // Not a failure, just a race the settlement path won.
            results.reminderSkipped++;
            continue;
          }

          notifyAdmin({
            subject: `⏰ Wire timed out — ${carLabel}`,
            html: alertHtml(
              `No wire received within ${WIRE_ABANDONMENT_TIMEOUT_BUSINESS_DAYS} business days`,
              [
                ["Vehicle", carLabel],
                ["Listing ID", listing.id],
                ["Buyer ID", listing.buyer_id ?? "—"],
                ["Agreed price", money(listing.sale_price)],
                ["Wire started", startedAtDate.toISOString().slice(0, 10)],
                ["Listing reopened", "yes — status set back to active"],
              ],
              "The listing is active again and open to other buyers. If the wire arrives late, it needs to be reconciled by hand — the PaymentIntent may still succeed after this point.",
            ),
          });

          results.expired++;
          continue;
        }

        // ── Day 2: one-shot buyer reminder ──────────────────────────────
        const reminderDueAt = new Date(startedAtDate.getTime());
        reminderDueAt.setDate(reminderDueAt.getDate() + REMINDER_AFTER_CALENDAR_DAYS);
        const reminderDue = now.getTime() >= reminderDueAt.getTime();

        if (!reminderDue || listing.wire_reminder_sent_at) {
          results.reminderSkipped++;
          continue;
        }

        if (dryRun) {
          results.reminded++;
          continue;
        }

        if (!listing.buyer_id) {
          results.reminderSkipped++;
          continue;
        }

        const { data: buyer } = await supabase
          .from("users")
          .select("name, email")
          .eq("id", listing.buyer_id)
          .maybeSingle();

        if (!buyer?.email) {
          results.reminderFailed++;
          results.errors.push(`${listing.id}: buyer has no email on file`);
          continue;
        }

        const sent = await sendEmail({
          to: buyer.email,
          subject: `Still waiting on your wire transfer for the ${carLabel}`,
          html: `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;color:#0f172a;max-width:520px;">
            <h2 style="font-size:18px;margin:0 0 14px;">We haven't seen your wire yet</h2>
            <p style="font-size:15px;line-height:1.55;">Your bank transfer for the <b>${carLabel}</b> hasn't arrived yet. This is just a check-in — nothing is wrong, but the listing stays reserved for you only while the transfer is in progress.</p>
            <p style="font-size:15px;line-height:1.55;">If you've already sent it, bank transfers can take a few business days — no action needed. If you haven't started it yet, please initiate it soon using the routing and account details from your original funding instructions.</p>
            <p style="font-size:14px;line-height:1.55;color:#374151;">If you've changed your mind or run into a problem, reply and let us know so we can free up the listing.</p>
            <p style="font-size:12px;color:#6b7280;margin-top:24px;">DriveLink · drivelink.deals</p>
          </div>`,
        });

        if (!sent) {
          results.reminderFailed++;
          results.errors.push(`${listing.id}: reminder email send failed`);
          continue;
        }

        // Stamp only after the send succeeds, so a failed attempt retries
        // on the next run instead of silently going unset forever.
        const { error: stampErr } = await supabase
          .from("listings")
          .update({ wire_reminder_sent_at: new Date().toISOString() })
          .eq("id", listing.id);

        if (stampErr) {
          results.errors.push(`${listing.id}: reminder sent but stamp failed — ${stampErr.message}`);
        }

        results.reminded++;
      } catch (e) {
        results.errors.push(`${listing.id}: ${e instanceof Error ? e.message : String(e)}`);
      }
    }

    const ms = Date.now() - startedAt;
    console.log(
      `expire-stale-wires: considered ${results.considered}, reminded ${results.reminded}, expired ${results.expired} in ${ms}ms`,
      results,
    );

    return jsonResponse({ ok: results.errors.length === 0, dryRun, ...results, ms });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("expire-stale-wires: fatal", message);

    // pg_cron logs success the moment the HTTP POST is queued, not when this
    // handler finishes — so a thrown error here is otherwise invisible.
    // Mandatory, awaited alert, same reasoning as auto-release-cron.
    await notifyAdminSync({
      subject: `⚠️ expire-stale-wires crashed`,
      html: alertHtml(
        "expire-stale-wires threw before finishing",
        [
          ["Error", message],
          ["Considered before failure", String(results.considered)],
          ["Reminded before failure", String(results.reminded)],
          ["Expired before failure", String(results.expired)],
        ],
        "pg_cron will show this run as dispatched successfully regardless — check Edge Function logs for the real outcome.",
      ),
    }).catch(() => {});

    return jsonResponse({ ok: false, error: message, ...results }, 500);
  }
});
